# Generated by Django 6.0.7 on 2026-08-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkresult',
            old_name='check_site',
            new_name='checkk',
        ),
    ]
